import Head from "next/head";
import { Button } from "antd";
import Image from "next/image";
import {useState} from 'react'
import { Inter } from "next/font/google";
import styles from "src/styles/Home.module.css";
import SinUp from './sinUp'
import Login from './login'
interface Props {}
const inter: any = Inter({ subsets: ["latin"] });


const Home: React.FC<Props> = () => {
  const [popUp,setPopUp]=useState(false)
  const [popUpLogin,setPopUpLogin]=useState(false)
  const togglePopup = () => {
    setPopUp(!popUp);
  };
  const togglePopupLogin = () => {
    setPopUpLogin(!popUpLogin);
  };
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Button onClick={togglePopupLogin}> Login</Button>
        {popUpLogin && <div className="overlay" ><Login/></div>}
        <Button onClick={togglePopup}> Signup</Button>
        {popUp && <div className="overlay"><SinUp /></div>}
        <div>
          <h1>ART is the work of god</h1>
        </div>
      </main>
    </>
  );
};

export default Home;
